# cluster specific values
cluster:
  # specify cluster name
  name: template-rke2

  # specify cluster labels
  labels: {}

  # specify cluster annotations
  annotations: {}

# specify cloud credential secret name, do not need to be provided if using custom driver
cloudCredentialSecretName: ""

# specify cloud provider, options are amazonec2, digitalocean, azure, vsphere or custom
cloudprovider: "digitalocean"

kubernetesVersion: ""

# general RKE options
rke:
  # enable local auth endpoint
  localClusterAuthEndpoint:
    enabled: false
  # specify fqdn of local access endpoint
  # fqdn: foo.bar.example
  # specify cacert of local access endpoint
  # caCerts: ""

# specify user principal ids to be assiged as cluster members
# clusterMembers:
# - principalName: "local://u-z8zl5"
#   roleTemplateName: "cluster-member"

# enable monitoring
monitoring:
  enabled: false
  # specify which version to install, can be semver range. If version is empty or is semver range, it will pick up the latest version.
  # version: ""
  # specify cutsom values set
  # values:
  #   foo: bar
